# Generated by Django 5.0.3 on 2026-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(max_length=255)),
                ('track', models.CharField(choices=[('1. Emerging and re-emerging infectious diseases', '1. Emerging and re-emerging infectious diseases'), ('2. Non-communicable diseases: monogenic and complex traits', '2. Non-communicable diseases: monogenic and complex traits'), ('3. Zoonotic spillover prevention in wildlife–livestock contact zones', '3. Zoonotic spillover prevention in wildlife–livestock contact zones'), ('4. Antimicrobial resistance at the human–animal–environment interface', '4. Antimicrobial resistance at the human–animal–environment interface'), ('5. Conservation, climate change and environmental health', '5. Conservation, climate change and environmental health'), ('6. Forensics, integrated data systems and Bio-surveillance', '6. Forensics, integrated data systems and Bio-surveillance'), ('7. Drug discovery and design', '7. Drug discovery and design'), ('8. Food security, biosecurity and safety', '8. Food security, biosecurity and safety')], max_length=100)),
                ('presentation_type', models.CharField(choices=[('Oral Presentation', 'Oral Presentation'), ('Poster Presentation', 'Poster Presentation')], max_length=50)),
                ('abstract_title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='abstracts/')),
                ('guidelines_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('General Support / Questions', 'General Support / Questions'), ('Abstract Submission Portal Support', 'Abstract Submission Portal Support'), ('Sponsorship & Exhibitor Space', 'Sponsorship & Exhibitor Space'), ('Payment & Invoicing Inquiries', 'Payment & Invoicing Inquiries')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('Other', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Undergraduate Student Pass', 'Undergraduate Student Pass (₦5,000)'), ('Postgraduate Delegate', 'Postgraduate Delegate (₦15,000)'), ('Academic & Regular Delegate', 'Academic & Regular Delegate (₦30,000)'), ('International Delegate', 'International Delegate ($100)')], max_length=50)),
                ('track', models.CharField(choices=[('Emerging and re-emerging infectious diseases', 'Emerging and re-emerging infectious diseases'), ('Non-communicable diseases: monogenic and complex traits', 'Non-communicable diseases: monogenic and complex traits'), ('Zoonotic spillover prevention in wildlife–livestock contact zones', 'Zoonotic spillover prevention in wildlife–livestock contact zones'), ('Antimicrobial resistance at the human–animal–environment interface', 'Antimicrobial resistance at the human–animal–environment interface'), ('Conservation, climate change and environmental health', 'Conservation, climate change and environmental health'), ('Forensics, integrated data systems and Bio-surveillance', 'Forensics, integrated data systems and Bio-surveillance'), ('Drug discovery and design', 'Drug discovery and design'), ('Food security, biosecurity and safety', 'Food security, biosecurity and safety')], max_length=100)),
                ('dietary_requirements', models.CharField(blank=True, max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('pref_plenary', models.BooleanField(default=True)),
                ('pref_poster', models.BooleanField(default=True)),
                ('pref_dinner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
