# Generated by Django 5.0.3 on 2026-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registration_technical_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='e.g. CEO, Commissioner, Professor', max_length=255)),
                ('affiliation', models.CharField(blank=True, help_text='e.g. Lagos State, LASEPA', max_length=255)),
                ('role', models.CharField(choices=[('Chairman', 'Chairman'), ('Special Guest of Honor', 'Special Guest of Honor'), ('Royal Father', 'Royal Father'), ('Special Guest', 'Special Guest')], max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Full bio / information for the read more page')),
                ('image_url', models.CharField(blank=True, help_text='Static image path (e.g. images/folawiyo.png) or full URL', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload custom image', null=True, upload_to='guests/')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
