# Generated by Django 5.0.3 on 2026-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_specialguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='e.g. Professor of Human Genetics, Managing Director', max_length=255)),
                ('affiliation', models.CharField(blank=True, help_text='e.g. University of Lagos', max_length=255)),
                ('role', models.CharField(choices=[('Keynote Speaker', 'Keynote Speaker'), ('Chairman of the Day', 'Chairman of the Day'), ('Plenary Speaker', 'Plenary Speaker'), ('Invited Speaker', 'Invited Speaker')], max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Full bio / information for the read more page')),
                ('image_url', models.CharField(blank=True, help_text='Static image path or full URL', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload custom image', null=True, upload_to='speakers/')),
                ('topic', models.CharField(blank=True, help_text='Presentation topic / research area', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
