# Generated by Django 5.0.3 on 2026-06-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
